version: '2'

services:
  test_db:
    image: postgres
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - data:/var/lib/POSTGRES
    environment:
      POSTGRES_ROOT_PASSWORD: some_password
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
    networks:
      - guac
  test_guacd:
    image: guacamole/guacd:0.9.14
    restart: always
    networks:
      - guac
  test_guac:
    image: guacamole/guacamole:0.9.14
    restart: always
    ports:
      - "8080:8080"
    links:
      - test_guacd
      - test_db
    environment:
      POSTGRES_HOSTNAME: test_db
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    networks:
      - guac
    depends_on:
      - test_db
      - test_guacd

volumes:
  data:
    driver: local

networks:
  guac:
    driver: bridge
